---

- name: Redis is Present locally
  find: 
    paths: "/home/{{ansible_user}}/{{working_directory}}/"
    file_type: directory
    use_regex: yes
    patterns: '.*redis-5*'
  register: redis_folder

# If not present install and compile

- name: Download binaries
  get_url:
    url: http://download.redis.io/releases/redis-5.0.8.tar.gz
    dest: "~/{{working_directory}}/redis-5.0.8.tar.gz"
  when: redis_folder.matched == 0
  register: downloaded_targz

- name: Extract files
  unarchive:
    src: "~/{{working_directory}}/redis-5.0.8.tar.gz"
    dest: "~/{{working_directory}}/"
    remote_src: yes
  when: downloaded_targz.changed
  register: extracted_targz

- name: Remove files
  command: rm "~/{{working_directory}}/redis-5.0.8.tar.gz"
  when: extracted_targz.changed and redis_folder.matched == 0

- name: Redis is Present locally after extraction
  find: 
    paths: "/home/{{ansible_user}}/{{working_directory}}/"
    file_type: directory
    use_regex: yes
    patterns: '.*redis-5*'
  register: redis_folder_extracted

- name: Compile Redis
  command: make
  args:
    chdir: "{{redis_folder_extracted.files[0].path}}"
  when: redis_folder_extracted.matched == 1
  register: result

- name: Debug Compile result
  debug:
    var: result
  when: redis_folder_extracted.matched == 1