---

- name: Install Open JDK 8
  become: yes
  become_method: sudo
  apt:
    pkg: openjdk-8-jre
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: Install Open JDK 8
  become: yes
  become_method: sudo
  yum:
    pkg: java-1.8.0-openjdk.x86_64
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes

- name: Cassandra is Present locally
  find: 
    paths: "/home/{{ansible_user}}/{{working_directory}}/"
    file_type: directory
    use_regex: yes
    patterns: '.*apache-cassandra-3.0.*'
  register: cassandra_folder

# If not present install

- name: Download binaries
  get_url:
    url: https://downloads.apache.org/cassandra/3.0.20/apache-cassandra-3.0.20-bin.tar.gz
    dest: "~/{{working_directory}}/apache-cassandra-3.0.20-bin.tar.gz"
  when: cassandra_folder.matched == 0
  register: downloaded_targz

- name: Extract files
  unarchive:
    src: "~/{{working_directory}}/apache-cassandra-3.0.20-bin.tar.gz"
    dest: "~/{{working_directory}}/"
    remote_src: yes
  when: downloaded_targz.changed
  register: extracted_targz


- name: Remove files
  command: rm "~/{{working_directory}}/apache-cassandra-3.0.20-bin.tar.gz"
  when: extracted_targz.changed and cassandra_folder.matched == 0


- name: Register folder
  find: 
    paths: "/home/{{ansible_user}}/{{working_directory}}/"
    file_type: directory
    use_regex: yes
    patterns: '.*apache-cassandra-3.0.*'
  register: cassandra_folder

- name: Copy template to cassandra
  template:
    src: templates/cassandra.yaml.j2
    dest: "{{ cassandra_folder.files[0].path }}/conf/cassandra.yaml"