---

- name: Etcd is Present locally
  find:
    paths: "/usr/local/bin/"
    use_regex: yes
    patterns: 'etcd.*'
  register: etcd_files

- name: Download Etcd Release v3.4.0
  get_url:
    url: https://storage.googleapis.com/etcd/v3.4.0/etcd-v3.4.0-linux-amd64.tar.gz
    dest: "~/{{working_directory}}/etcd-v3.4.0-linux-amd64.tar.gz"
  when: etcd_files.matched == 0
  register: downloaded_targz

- name: Extract files
  unarchive:
    src: "~/{{working_directory}}/etcd-v3.4.0-linux-amd64.tar.gz"
    dest: ~/
    remote_src: yes
  when: downloaded_targz.changed
  register: extracted_targz

- name: Remove files
  command: "rm ~/{{working_directory}}/etcd-v3.4.0-linux-amd64.tar.gz"
  when: extracted_targz.changed

- name: Etcd is Present locally after extraction
  find:
    paths: "/home/{{ansible_user}}/{{working_directory}}/"
    file_type: directory
    use_regex: yes
    patterns: 'etcd-v3.4.0.*$'
  register: etcd_folder_extracted
  
- name: Move files to /usr/local/bin
  command:  
    cmd: cp -t /usr/local/bin/ etcd etcdctl
    chdir: "{{etcd_folder_extracted.files[0].path}}"
  become: yes
  when: etcd_folder_extracted.matched != 0
    
- name: Check that group exists
  group:
      name: etcd
      state: present # not required. choices: absent;present. Whether the group should be present or not on the remote host.
      gid: 1501 # not required. Optional I(GID) to set for the group..
  become: yes
  register: group_exists

- name: Add the user 'etcd' with a uid 1202 and a primary group of 'etcd'
  user:
    comment: etcd admin user
    name: etcd
    uid: 1202
    group: etcd
    groups: "{{ansible_user}},etcd"
    home: /var/lib/etcd
    shell: /bin/false
    update_password: always
    password: "{{ etcdpass | password_hash('sha512')}}"
  become: yes
  ignore_errors: yes

- name: Change etcd home permissions
  file:
    path: /var/lib/etcd
    state: directory
    group: etcd
    owner: etcd
    recurse: yes
  become: yes

- name: Add the template to systemd
  template:
      dest: /lib/systemd/system/etcd.service
      src:  templates/etcd.service.j2
  become: yes