---

- name: Register folder
  find: 
    paths: "/home/{{remote_user}}/"
    file_type: directory
    use_regex: yes
    patterns: '.*apache-cassandra-3.0.*'
  register: cassandra_folder

- name: Start cassandra on background
  shell: "{{cassandra_folder.files[0].path}}/bin/cassandra -p cassandra_pid"

  
- name: Copy cqlsh commands
  copy:
    src: files/create_db.cql
    dest: ~/create_db.cql
    
- name: Write DB if not initialized
  shell: "{{cassandra_folder.files[0].path}}/bin/cqlsh -f ~/create_db.cql"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 15